# Generated by Django 3.0.5 on 2020-07-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Quiz')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='games',
            field=models.ManyToManyField(through='quizapp.Game', to='quizapp.Team'),
        ),
    ]
