# Generated by Django 3.0.5 on 2020-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20200723_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='q/'),
        ),
        migrations.AddField(
            model_name='team',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='t/'),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('ff', 'Fact or Fiction'), ('gk', 'General Knowledge'), ('pic', 'Picture Round'), ('aud', 'Audio Round'), ('sp', 'Spotlight Round'), ('an', 'Analysis Round'), ('b', 'Bonus Round')], max_length=200),
        ),
    ]
