# Generated by Django 3.0.5 on 2020-09-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FencingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref1_type', models.CharField(choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1)),
                ('ref1', models.CharField(max_length=20)),
                ('ref2_type', models.CharField(choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1)),
                ('ref2', models.CharField(max_length=20)),
                ('ref3_type', models.CharField(choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1)),
                ('ref3', models.CharField(max_length=20)),
                ('ref4_type', models.CharField(choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1)),
                ('ref4', models.CharField(max_length=20)),
                ('ref5_type', models.CharField(choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1)),
                ('ref5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=12)),
                ('device_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point_time', models.DateTimeField()),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.FencingModule')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Load')),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='tracker_chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.TrackerChip'),
        ),
    ]
