# Generated by Django 3.0.5 on 2020-09-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fencingmodule',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fencingmodule',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fencingmodule',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='fencingmodule',
            name='state',
        ),
        migrations.RemoveField(
            model_name='fencingmodule',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='load',
            name='tracker_chip',
        ),
        migrations.AddField(
            model_name='load',
            name='tracker_chips',
            field=models.ManyToManyField(through='geo.Trip', to='geo.TrackerChip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='trip',
            name='tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.TrackerChip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='device_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='check_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.FencingModule'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='check_point_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fencingmodule',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AddField(
            model_name='load',
            name='dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='geo.Location'),
        ),
        migrations.AddField(
            model_name='load',
            name='orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig', to='geo.Location'),
        ),
        migrations.AddField(
            model_name='trackerchip',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Client'),
        ),
    ]
