# Generated by Django 3.0.5 on 2020-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200918_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='ref1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref1_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref2_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref3_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref4_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref5_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order')], max_length=1, null=True),
        ),
    ]
