# Generated by Django 3.0.5 on 2020-09-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20200919_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fencingmodule',
            name='device_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref1_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref2_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref3_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref4_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='ref5_type',
            field=models.CharField(blank=True, choices=[('L', 'Load ID'), ('B', 'Bill of Lading'), ('P', 'PRO Number'), ('R', 'Purchase Order'), ('S', 'Sales Order'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='device_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
