# Generated by Django 3.0.5 on 2020-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20200919_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerchip',
            old_name='tracker_id',
            new_name='device_id',
        ),
        migrations.AddField(
            model_name='fencingmodule',
            name='device_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
