# Generated by Django 3.0.5 on 2020-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20200926_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fencingmodule',
            name='device_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='device_id',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='device_name',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
