# Generated by Django 2.1.4 on 2020-10-05 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20201002_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fencingmodule',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 12, 35, 47, 963794)),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 12, 35, 47, 963794)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
