# Generated by Django 3.1.2 on 2020-10-09 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20201007_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fencingmodule',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 22, 53, 22, 487991)),
        ),
        migrations.AlterField(
            model_name='trackerchip',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 22, 53, 22, 489986)),
        ),
    ]
